name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: kepkin/kong-react-admin

    steps:
    - uses: actions/checkout@v2
    - name: React
      run: docker build
